# SITE CONFIGURATION
title: Aileen Zeng # your site title
author: aileenzeng # You :P
description: > # Meta description of Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aileenzeng.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Aileen Zeng
  links:
    - https://twitter.com/_aileenz_
    - https://www.linkedin.com/in/aileen-zeng
    - https://github.com/aileenzeng

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Blog', link: '/blog'}
  - {name: 'Resume', link: '/resume'}

tagline: >
  Hello! I'm Aileen.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: aileenz@cs.washington.edu # email for form submission

twitter_username: _aileenz_ # replace with your_twitter_username or comment to remove link from footer
github_username:  aileenzeng # replace with your_github_username or comment to remove link from footer
linkedin_username: aileen-zeng
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: aileen # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg
  - .idea

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
